[package]
name = "auto_graph"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true  # Problematic with webassembly ?
opt-level = 3

[dependencies]
eframe = "0.19.0"
